-- 30_sidebar_left.lua — the file explorer column.
--
-- **Reserved for PLAN §P7 L2.** It is deliberately absent rather than filled with a
-- placeholder: sessions are the tab bar now (20_header.lua), so a session list here would
-- be the same information twice, and an empty frame would look like a bug.
--
-- L2 adds `TUI.build_explorer(width, height)` here, fed by the same Rust file index that
-- backs the `@` mention dropdown and the centre-top viewer (one walk, three surfaces —
-- PLAN §P7 D6). `90_render.lua` already reserves the column, gated on
-- `TUI.EXPLORER_VISIBLE`.
