-- 30_sidebar_left.lua — the file explorer column (PLAN §P7 L2 / D3).
--
-- The tree itself is a **native view**: `{type="native", view="explorer"}`, placed by
-- `90_render.lua` and fed by the one Rust file index that also backs the `@` dropdown and the
-- viewer (D6). Nothing is defined here because there is nothing for Lua to decide beyond the
-- placement — and the placement already lives in `90_render.lua` next to the other columns.
--
-- Visibility is Rust's: `F1` toggles `kn9t.state.explorer_visible` and the keyboard focus with
-- it (`toggle_explorer`), so a user binding F1 would fight the host. Width is
-- `TUI.EXPLORER_WIDTH`; keys while focused are arrows/Left/Right/Enter/`m`/Esc.
