//! Generators for `schema/generated/go_types.go` and `schema/generated/python_types.py`.
//!
//! Purpose (ADR-0005, F11): a `pub` field whose type has no `pub` constructor is a
//! **compile-time-invisible contract break** — only consumers in another language
//! would notice. The Go stub is consumed by `plugins/kn9t-agents-md` and the Python
//! stub by `plugins/kn9t-mcp`; when the schema changes, these files change, and a
//! plugin that re-derives the wire contract cannot silently disagree with the server.

use std::path::Path;

use serde_json::Value;

use crate::schema::{properties, req_name_for_path, required, routes};

const GO_HEADER: &str = "// Code generated by xtask. DO NOT EDIT.
// Source: schema/http.json + schema/plugin.json (ADR-0005).
// Regenerate with `cargo run -p xtask -- generate`.
// These types mirror the server's request bodies; a schema change that breaks a
// plugin is a *compile error here*, not a silent mismatch at runtime.

package schema
";

const PY_HEADER: &str = "# Code generated by xtask. DO NOT EDIT.
# Source: schema/http.json + schema/plugin.json (ADR-0005).
# Regenerate with `cargo run -p xtask -- generate`.
# These types mirror the server's request bodies; a schema change that breaks a
# plugin is a *NameError/TypeError here*, not a silent mismatch at runtime.

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
";

pub fn write(root: &Path, http: &Value, plugin: &Value) -> Result<(), String> {
    let (go, py) = generate(http, plugin)?;
    let dir = root.join("schema/generated");
    std::fs::create_dir_all(&dir).map_err(|e| format!("create schema/generated: {e}"))?;
    std::fs::write(dir.join("go_types.go"), go.as_bytes())
        .map_err(|e| format!("write go_types.go: {e}"))?;
    std::fs::write(dir.join("python_types.py"), py.as_bytes())
        .map_err(|e| format!("write python_types.py: {e}"))?;
    Ok(())
}

pub fn generate(http: &Value, plugin: &Value) -> Result<(String, String), String> {
    // HTTP request payloads — the same set api.rs derives.
    let requests: Vec<(String, &Value)> = routes(http)
        .iter()
        .filter(|r| r.method == "POST")
        .filter_map(|r| {
            let obj = r.request_object()?;
            let name = req_name_for_path(r.path)?;
            Some((name.to_string(), obj))
        })
        .collect();

    // Plugin protocol definitions.
    let defs: Vec<(String, &Value)> = plugin
        .get("definitions")
        .and_then(|d| d.as_object())
        .map(|o| o.iter().map(|(k, v)| (k.clone(), v)).collect())
        .unwrap_or_default();

    Ok((go_types(&requests, &defs), python_types(&requests, &defs)))
}

// ── Go ─────────────────────────────────────────────────────────────────────────

fn go_types(requests: &[(String, &Value)], defs: &[(String, &Value)]) -> String {
    let mut s = String::new();
    s.push_str(GO_HEADER);
    s.push_str("\n// ModelRef — the shared `{provider, id}` reference.\n");
    s.push_str("type ModelRef struct {\n");
    s.push_str("\tProvider string `json:\"provider\"`\n");
    s.push_str("\tID       string `json:\"id\"`\n");
    s.push_str("}\n\n");

    for (name, obj) in requests {
        s.push_str(&format!("// {name} — request body.\n"));
        s.push_str(&format!("type {name} struct {{\n"));
        let req = required(obj);
        for (key, prop) in properties(obj) {
            let (ty, optional) = go_field(prop, &req, &key);
            let json_tag = if optional {
                format!("`json:\"{key},omitempty\"`")
            } else {
                format!("`json:\"{key}\"`")
            };
            s.push_str(&format!(
                "\t{key_go} {ty} {json_tag}\n",
                key_go = go_ident(&key)
            ));
        }
        s.push_str("}\n\n");
    }

    s.push_str("// Plugin protocol definitions (schema/plugin.json).\n");
    for (name, subschema) in defs {
        s.push_str(&format!("// {name}.\n"));
        s.push_str(&format!("type {name} struct {{\n"));
        let req = required(subschema);
        for (key, prop) in properties(subschema) {
            let (ty, optional) = go_field(prop, &req, &key);
            let json_tag = if optional {
                format!("`json:\"{key},omitempty\"`")
            } else {
                format!("`json:\"{key}\"`")
            };
            s.push_str(&format!(
                "\t{key_go} {ty} {json_tag}\n",
                key_go = go_ident(&key)
            ));
        }
        s.push_str("}\n\n");
    }
    s
}

fn go_ident(key: &str) -> String {
    // snake_case → Go exported CamelCase (id → ID, ctx_window → CtxWindow).
    let parts: Vec<&str> = key.split('_').collect();
    let mut out = String::new();
    for p in parts {
        let mut c = p.chars();
        if let Some(first) = c.next() {
            if p == "id" {
                out.push_str("ID");
            } else {
                out.extend(first.to_uppercase());
                out.push_str(c.as_str());
            }
        }
    }
    out
}

fn go_field(prop: &Value, req: &[String], key: &str) -> (String, bool) {
    let optional = !req.iter().any(|r| r.as_str() == key);
    let base = go_prim(prop);
    if optional {
        (format!("*{base}"), true)
    } else {
        (base, false)
    }
}

fn go_prim(prop: &Value) -> String {
    let mut nullable = false;
    let mut prim = "";
    match prop.get("type") {
        Some(t) if t.is_string() => prim = t.as_str().unwrap_or(""),
        Some(t) if t.is_array() => {
            for m in t.as_array().into_iter().flatten() {
                match m.as_str() {
                    Some("null") => nullable = true,
                    Some(o) => prim = o,
                    None => {}
                }
            }
        }
        _ => {}
    }
    let base = match prim {
        "string" => "string".to_string(),
        "integer" => "uint64".to_string(),
        "number" => "float64".to_string(),
        "boolean" => "bool".to_string(),
        "array" => {
            let item_ty = prop
                .get("items")
                .and_then(|i| i.get("type"))
                .and_then(|t| t.as_str())
                .unwrap_or("object");
            match item_ty {
                "string" => "[]string".to_string(),
                _ => "[]map[string]any".to_string(),
            }
        }
        "object" => {
            if crate::schema::is_model_ref(prop) {
                "ModelRef".to_string()
            } else {
                "map[string]any".to_string()
            }
        }
        _ => "any".to_string(),
    };
    if nullable {
        format!("*{base}")
    } else {
        base
    }
}

// ── Python ─────────────────────────────────────────────────────────────────────

fn python_types(requests: &[(String, &Value)], defs: &[(String, &Value)]) -> String {
    let mut s = String::new();
    s.push_str(PY_HEADER);
    s.push_str("\n\n@dataclass\nclass ModelRef:\n    \"\"\"The shared `{provider, id}` reference.\"\"\"\n\n");
    s.push_str("    provider: str\n");
    s.push_str("    id: str\n");

    for (name, obj) in requests {
        s.push_str(&format!(
            "\n\n@dataclass\nclass {name}:\n    \"\"\"Request body.\"\"\"\n\n"
        ));
        let req = required(obj);
        for (key, prop) in properties(obj) {
            let ty = py_type(prop);
            let optional = !req.iter().any(|r| r == &key);
            let (ann, default) = if optional {
                (format!("Optional[{ty}]"), " = None")
            } else {
                (ty, "")
            };
            s.push_str(&format!("    {key}: {ann}{default}\n"));
        }
    }

    s.push_str("\n\n# Plugin protocol definitions (schema/plugin.json).\n");
    for (name, subschema) in defs {
        s.push_str(&format!(
            "\n@dataclass\nclass {name}:\n    \"\"\"Plugin protocol definition.\"\"\"\n\n"
        ));
        let req = required(subschema);
        for (key, prop) in properties(subschema) {
            let ty = py_type(prop);
            let optional = !req.iter().any(|r| r == &key);
            let (ann, default) = if optional {
                (format!("Optional[{ty}]"), " = None")
            } else {
                (ty, "")
            };
            s.push_str(&format!("    {key}: {ann}{default}\n"));
        }
    }
    s.push_str("\n");
    s
}

fn py_type(prop: &Value) -> String {
    let mut nullable = false;
    let mut prim = "";
    match prop.get("type") {
        Some(t) if t.is_string() => prim = t.as_str().unwrap_or(""),
        Some(t) if t.is_array() => {
            for m in t.as_array().into_iter().flatten() {
                match m.as_str() {
                    Some("null") => nullable = true,
                    Some(o) => prim = o,
                    None => {}
                }
            }
        }
        _ => {}
    }
    let base = match prim {
        "string" => "str".to_string(),
        "integer" => "int".to_string(),
        "number" => "float".to_string(),
        "boolean" => "bool".to_string(),
        "array" => {
            let item_ty = prop
                .get("items")
                .and_then(|i| i.get("type"))
                .and_then(|t| t.as_str())
                .unwrap_or("object");
            match item_ty {
                "string" => "List[str]".to_string(),
                _ => "List[Dict[str, Any]]".to_string(),
            }
        }
        "object" if crate::schema::is_model_ref(prop) => "ModelRef".to_string(),
        "object" => "Dict[str, Any]".to_string(),
        _ => "Any".to_string(),
    };
    if nullable {
        format!("Optional[{base}]")
    } else {
        base
    }
}
